name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
    - name: Test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
    - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
      with:
        version: v2.4.0
