name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - stable
        - oldstable
    runs-on: ubuntu-22.04
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        cache: true
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        cache: true
        go-version: stable
    - uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804
      with:
        version: v1.59.1