name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - 1.x
        - 1.18.x
        os:
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
        cache: true
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
        cache: true
        go-version: 1.x
    - uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1
      with:
        version: v1.50.1