name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - stable
        - oldstable
        runs-on:
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        cache: true
        go-version: stable
    - uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64
      with:
        version: v1.61.0